slam_toolbox:
  ros__parameters:
    # Robot frame settings
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan

    # SLAM parameters
    use_sim_time: true
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 20.0
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000

    # Loop closure parameters
    loop_search_space_dimension: 8.0
    loop_match_minimum_chain_size: 3
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45