controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.25
    wheel_radius: 0.05

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.5 # m/s
        has_acceleration_limits: true
        max_acceleration: 1.0 # m/s^2
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0 # rad/s
        has_acceleration_limits: true
        max_acceleration: 2.0 # rad/s^2

    # If true, publish the wheel joint states as a joint_states message
    publish_wheel_joint_states: true

    # If true, enable open loop control
    open_loop: false

    # Velocity command timeout
    cmd_vel_timeout: 0.5 # seconds

    # Base frame ID
    base_frame_id: base_link

    # Odom frame ID
    odom_frame_id: odom

    # Enable odom tf publishing
    enable_odom_tf: true

    # Publish rate for odom and tf
    publish_rate: 50.0

    # Velocity and position feedback gains
    position_feedback: true
    position_gain: 0.5
    velocity_gain: 0.5

    # Use mixed-case names for the parameters
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

    # Publish wheel joint states
    publish_wheel_data: true

    # Wheel slip parameters
    wheel_slip_factor: 0.0

    # Transform timeout
    tf_timeout: 0.1