<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Define properties needed for gazebo plugins -->
  <xacro:property name="wheel_radius" value="0.1" />
  <xacro:property name="wheel_offset_y" value="0.175" />

  <!-- Gazebo-specific robot configuration -->
  <gazebo reference="$(arg robot_namespace)/base_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="$(arg robot_namespace)/left_wheel">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <minDepth>0.001</minDepth>
    <maxVel>1.0</maxVel>
  </gazebo>

  <gazebo reference="$(arg robot_namespace)/right_wheel">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <minDepth>0.001</minDepth>
    <maxVel>1.0</maxVel>
  </gazebo>

  <gazebo reference="$(arg robot_namespace)/caster_wheel">
    <material>Gazebo/Black</material>
    <mu1>0.1</mu1>
    <mu2>0.1</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <minDepth>0.001</minDepth>
    <maxVel>1.0</maxVel>
  </gazebo>

  <gazebo reference="$(arg robot_namespace)/lidar_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- Differential Drive Controller Plugin -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <!-- Plugin update rate -->
      <update_rate>30</update_rate>

      <!-- Left/Right wheel joints -->
      <left_joint>$(arg robot_namespace)/left_wheel_joint</left_joint>
      <right_joint>$(arg robot_namespace)/right_wheel_joint</right_joint>

      <!-- Robot characteristics -->
      <wheel_separation>${wheel_offset_y * 2}</wheel_separation>
      <wheel_diameter>${wheel_radius * 2}</wheel_diameter>

      <!-- Limits -->
      <max_wheel_acceleration>1.0</max_wheel_acceleration>
      <max_wheel_torque>20</max_wheel_torque>

      <!-- Command topic -->
      <command_topic>cmd_vel</command_topic>

      <!-- Odometry output -->
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>
      <odometry_topic>odom</odometry_topic>
      <odometry_frame>$(arg robot_namespace)/odom</odometry_frame>
      <robot_base_frame>$(arg robot_namespace)/base_footprint</robot_base_frame>

      <!-- Publishers -->
      <ros>
        <remapping>odom:=odom</remapping>
        <remapping>cmd_vel:=cmd_vel</remapping>
      </ros>
    </plugin>
  </gazebo>

  <!-- LiDAR Sensor -->
  <gazebo reference="$(arg robot_namespace)/lidar_link">
    <sensor type="ray" name="lidar">
      <pose>0 0 0 0 0 0</pose>
      <update_rate>5</update_rate>
      <visualize>true</visualize>
      <ray>
        <scan>
          <horizontal>
            <samples>120</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>2.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="lidar_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <remapping>~/out:=scan</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>$(arg robot_namespace)/lidar_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Joint State Publisher -->
  <gazebo>
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <ros>
        <remapping>~/out:=joint_states</remapping>
      </ros>
      <update_rate>30</update_rate>
      <joint_name>$(arg robot_namespace)/left_wheel_joint</joint_name>
      <joint_name>$(arg robot_namespace)/right_wheel_joint</joint_name>
    </plugin>
  </gazebo>

</robot>